apiVersion: skaffold/v3
kind: Config
metadata:
  name: postgres_config
deploy:
  helm:
    releases:
      - name: "postgres"
        remoteChart: postgresql
        valuesFiles:
          - "k8s-services/postgres/values-postgres-{{.SITE}}.yaml"
        namespace: "postgres-{{.SITE}}"
        createNamespace: true
        repo: https://charts.bitnami.com/bitnami
        upgradeOnChange: true
      - name: "adminer"
        remoteChart: adminer
        valuesFiles:
          - "k8s-services/postgres/values-adminer-{{.SITE}}.yaml"
        namespace: "postgres-{{.SITE}}"
        createNamespace: true
        repo: https://cetic.github.io/helm-charts
        upgradeOnChange: true
